version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 1
    groups:
      github-actions-weekly:
        applies-to: "version-updates"
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 1
    groups:
      npm-weekly:
        applies-to: "version-updates"
        patterns: ["*"]
        update-types: ["minor", "patch"]
