name: 'foundry-toolchain'
description: 'Install Foundry'
author: 'Oliver Nordbjerg'
branding:
  icon: play-circle
  color: black
inputs:
  version:
    description: |
      Foundry version.

      This version number has to match a released version of Foundry.
      Alternatively you can also specify `nightly` for the latest nightly build.
  token:
    description: |
      Authorized GitHub token.

      Defaults to `github.token`.
    required: false
    default: ${{ github.token }}

runs:
  using: node16
  main: dist/index.js
