name: "foundry-toolchain"
description: "Install Foundry"
author: "Foundry"
branding:
  color: "gray-dark"
  icon: "play-circle"

inputs:
  version:
    default: "stable"
    description: |
      Foundry version.

      This version number has to match a released version of Foundry.
      The default value is `stable`, which will pull the latest stable build.
    required: false
  network:
    default: "ethereum"
    description: |
      Network to install Foundry for.

      This can be either `ethereum` or `tempo`. The default value is `ethereum`.
    required: false
  cache:
    default: "true"
    description: |
      Whether to cache RPC responses or not.

      Caching is activated by default.
    required: false
  cache-key:
    default: "${{ github.job }}-${{ github.sha }}"
    description: |
      A custom cache key to use.

      This key is used to identify the cache. If not provided, a default key consisting of the job id and the commit hash is used.
    required: false
  cache-restore-keys:
    default: |-
      ${{ github.job }}-
    description: |
      Custom cache restore keys to use.

      This key is used to identify the cache to restore. If not provided, a default key consisting of the job id is used.
    required: false

runs:
  using: "node24"
  main: "dist/index.js"
  post: "dist/save/index.js"
  post-if: success()
